using Tyuiu.AlshinAF.Sprint5.Task4.V26.Lib;
DataService ds = new DataService();
Console.Title = "Спринт #5 | Выполнил: Альшин А. Ф. | РППб-24-1";
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Спринт #5                                                               *");
Console.WriteLine("* Тема:  Класс File. Запись набора данных в текстовый файл                *");
Console.WriteLine("* Задание #5                                                              *");
Console.WriteLine("* Вариант #26                                                             *");
Console.WriteLine("* Выполнил: Альшин Артур Фаритович | РППб-24-1                            *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                *");
Console.WriteLine("* Дан двумерный целочисленный массив 3 на 3 элементов, заполненный        *");
Console.WriteLine("* значениями с клавиатуры. Заменить нечетные элементы массива на 0.       *");
Console.WriteLine("* Результат сохранить в файл OutPutFileTask2.csv и вывести на консоль     *");
Console.WriteLine("*                                                                         *");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                        *");
Console.WriteLine("***************************************************************************");
string path = Path.GetTempFileName();
Console.WriteLine("Данные находится в файле: " + path);
Console.WriteLine("***************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                              *");
Console.WriteLine("***************************************************************************");
Console.WriteLine(ds.LoadFromDataFile(path));
Console.ReadKey();