using Tyuiu.AlshinAF.Sprint5.Task4.V26.Lib;
DataService ds = new DataService();
Console.Title = "Спринт #5 | Выполнил: Альшин А. Ф. | РППб-24-1";
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Спринт #5                                                               *");
Console.WriteLine("* Тема:  Потоковый метод записи данных в бинарный файл                    *");
Console.WriteLine("* Задание #4                                                              *");
Console.WriteLine("* Вариант #26                                                             *");
Console.WriteLine("* Выполнил: Альшин Артур Фаритович | РППб-24-1                            *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                *");
Console.WriteLine("* Дан файл в котором есть вещественное значение. Прочитать значение из    *");
Console.WriteLine("* подставить вместо Х в формуле. Вычислить значение по формуле и вернуть  *");
Console.WriteLine("* полученный результат на консоль                                         *");
Console.WriteLine("*                                                                         *");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                        *");
Console.WriteLine("***************************************************************************");
string path = Path.GetTempFileName();
Console.WriteLine("Данные находится в файле: " + path);
Console.WriteLine("***************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                              *");
Console.WriteLine("***************************************************************************");
Console.WriteLine(ds.LoadFromDataFile(path));
Console.ReadKey();